language: node_js
node_js:
  - "6.3"

sudo: false

os:
  - linux

before_install:
  - npm install -g typescript
  - npm install -g tslint

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent